### ISSUE TITLE
Usage with SQLX

### ISSUE THREAD

**Issue by Niels-Be** [nyurik/sqlite-hashes#32]
Hi, how can this be used together with  [sqlx](https://github.com/launchbadge/sqlx)?
I saw references to it in the cargo.toml but did not find any documentation about it.

Its unclear to me how I can get to the `rusqlite::Connection` from an `sqlx::SqlitePool` in order to call `register_hash_functions`.

Also does this have to be called for every connection from the pool?

**Comment by nyurik** [comment]
@Niels-Be hi, I use it with sqlx here:

https://github.com/maplibre/martin/blob/ff16f9a82090f711ac4d03831f39d4f14580b6e1/mbtiles/src/mbtiles.rs#L222

I think you need to register the plugin on every connection, e.g. using [after_connect](https://docs.rs/sqlx/latest/sqlx/pool/struct.PoolOptions.html#method.after_connect).  Looking at the sqlite docs, [sqlite3_load_extension](https://sqlite.org/c3ref/load_extension.html) requires `sqlite3 *db` (documented as *Load the extension into this database connection*) - so it seems that every connection must load it.

**Comment by nyurik** [comment]
This is now [documented](https://github.com/nyurik/sqlite-hashes?tab=readme-ov-file#using-with-sqlx) in the README
