### ISSUE TITLE
Add FNV non-cryptographic hashing function

### ISSUE THREAD

**Issue by jessekrubin** [nyurik/sqlite-hashes#6]
Tippecannoe v2 uses fn1va for it's tile_id column. Curious how involved adding fnv1a to this lib.

**Comment by nyurik** [comment]
I'm all for it, and it, in theory :), should not be very difficult.  There [seem to be](https://crates.io/search?q=fnv) a number of FNV implementations already. Unfortunately, the `Digest` or `NamedDigest` traits do not seem to be implemented for any of the FNV crates, so we would have to duplicate some code that instantiates function registration and hash computation, but shouldn't be too difficult.  Want to take a stab at it?

**Comment by nyurik** [comment]
@jessekrubin here, i implemented a lib https://github.com/nyurik/noncrypto-digests . Use that to add it to this lib - should be just a few lines, plus run `just bless`.  You may also want to implement CRC32 and other fun hashes for completeness.

**Comment by nyurik** [comment]
P.S. I forgot to expose the right object. Fixed now in v0.2.0

**Comment by nyurik** [comment]
> For sure I can take a stab. Might need some guidance. Looked at Digest trait, but am not sure what NamedDigest is.

Don't worry about the `NamedDigest` -- it is used inside the `digest_names` macro to add a name to the type. Search for `digest_names!`

> 
> For just the hash tho (specifically for tiles) why is the digest trait needed? Not questioning just curious.

Now with the `noncrypto-digests` crate, you can trean Fnv exactly the same as md5 or sha256 - so just copy/paste that code and adjust the names of functions, and it should "just work".

> 
> I think it would be a nice addition if it yielded smaller tile_ids. Could the tile_id then be an int as opposed to a hexstr?

Technically the tile id can be anything - mbtiles specification does NOT specify what "normalized" table schema should look like (normalized == having `map` and `images` tables). The specification simply requires the `tiles` table OR view.  The view in this case can use an integer as a foreign key to link two tables - which may be faster (performance testing is needed).

Note that the Martin project did standardize the "normalized" schema [here](https://maplibre.org/martin/mbtiles-schema.html#normalized), and it did use `TEXT` for the ID.  It should be fairly simple to add another type there, like `normalized-int` to make it support the type "properly".

**Comment by jessekrubin** [comment]
I will try to get to it this weekend. 

I figure an int hash would be smaller and possibly faster but idk...

pre finding martin/mbtiles-cli I had this not very pretty script to do the normalizing (needs the crypto squeal-lite extension to work):

<details><summary>squeal-lite-norm-script</summary>
<p>

```sql
-- SQLITE!
.echo on
-- load the crypto module
PRAGMA auto_vacuum = FULL;

.load ./crypto

-- BEGIN;
CREATE TABLE IF NOT EXISTS images
(
    tile_data blob,
    tile_id   text
);

CREATE TABLE IF NOT EXISTS map
(
    zoom_level  INTEGER,
    tile_column INTEGER,
    tile_row    INTEGER,
    tile_id     TEXT
);

CREATE TABLE IF NOT EXISTS tmpmap
(
    zoom_level  INTEGER,
    tile_column INTEGER,
    tile_row    INTEGER,
    tile_id     TEXT,
    tile_data   BLOB
);

--   clear the tmpmap table
DELETE
FROM tmpmap;


SELECT *
FROM tmpmap;

INSERT INTO tmpmap (zoom_level, tile_column, tile_row, tile_id, tile_data)
SELECT zoom_level, tile_column, tile_row, hex(md5(tile_data)), tile_data
FROM tiles;

INSERT INTO map (zoom_level, tile_column, tile_row, tile_id)
SELECT zoom_level, tile_column, tile_row, tile_id
FROM tmpmap
WHERE tile_id NOT IN (SELECT tile_id FROM map);

INSERT INTO images (tile_data, tile_id)
SELECT DISTINCT tile_data, tile_id
FROM tmpmap
WHERE tile_id NOT IN (SELECT tile_id FROM images);

ALTER TABLE tiles
    RENAME TO tiles_old;

CREATE UNIQUE INDEX IF NOT EXISTS map_index ON map (zoom_level, tile_column, tile_row);
CREATE UNIQUE INDEX IF NOT EXISTS images_id ON images (tile_id);

CREATE VIEW IF NOT EXISTS tiles AS
SELECT map.zoom_level   AS zoom_level,
       map.tile_column  AS tile_column,
       map.tile_row     AS tile_row,
       images.tile_data AS tile_data
FROM map
         JOIN images ON images.tile_id = map.tile_id;

DROP TABLE tiles_old;
DROP TABLE tmpmap;
VACUUM;
```

</p>
</details>
